### ISSUE TITLE
FAILED to install kernel

### ISSUE THREAD

**Issue by astalush** [tmiland/kernel-installer#12]
LD [M]  drivers/gpu/drm/drm_kms_helper.o
  LD [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.o
  AR      drivers/gpu/built-in.a
make[4]: *** [scripts/Makefile.build:500: drivers] Error 2
make[3]: *** [Makefile:1992: .] Error 2
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:86: bindeb-pkg] Error 2
make: *** [Makefile:1636: bindeb-pkg] Error 2
Compiling The Linux Kernel source code...: [2023-01-10 15:58:56 CET] [ERROR] Failed with error: 2
[2023-01-10 15:58:56 CET] [ERROR] Something went wrong. Exiting.
[2023-01-10 15:58:56 CET] [ERROR] The last few log entries were:
Spin pid is: 1627617
dpkg: error: cannot access archive 'linux-headers-6.1.4_6.1.4-*.deb': No such file or directory
Made it here...why?
Installing Kernel headers: 6.1.4: [2023-01-10 15:58:56 CET] [ERROR] Failed with error: 2
[2023-01-10 15:58:56 CET] [ERROR] Something went wrong. Exiting.
[2023-01-10 15:58:56 CET] [ERROR] The last few log entries were:

Can someone help?

**Comment by tmiland** [comment]
Hello,

could you provide the full log?

**Comment by astalush** [comment]
[kernel_installer.log](https://github.com/tmiland/kernel-installer/files/10384247/kernel_installer.log)

**Comment by astalush** [comment]
Any leads? :)

**Comment by tmiland** [comment]
> Any leads? :)

Hold on :)

**Comment by tmiland** [comment]
Okay, have tested multiple times now, and get the same error, so something must have changed,
but cannot figure out why right now. I'll look into it later.

Sorry for the inconvenience.

**Comment by astalush** [comment]
No inconvenience at all my friend, take your time. It's strange it worked like in december (when I used it) but now with the 6.1.4 (even with 6.1.2) doesn't work.
I think the problem it's something with the amd gpu libs / drivers or maybe something else. 

Thanks for your time :)

**Comment by tmiland** [comment]
Okay, installed successfully with:

```bash
./kernel_installer.sh -s -d /home/linux -gvt
```
Not sure why, but i think enough disk space is needed perhaps.
The .deb packages are created correctly, and the script should find them.

Weird stuff.

**Comment by astalush** [comment]
/dev/nvme0n1p2  931G  256G  671G  28% /

I don't think the disk space is the problem for me :-D

**Comment by astalush** [comment]
Nup, same thing, 

[ERROR] Something went wrong. Exiting.
[ERROR] The last few log entries were:
  AR      drivers/net/built-in.a
make[4]: *** [scripts/Makefile.build:500: drivers] Error 2
make[3]: *** [Makefile:1992: .] Error 2
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:86: bindeb-pkg] Error 2
make: *** [Makefile:1636: bindeb-pkg] Error 2
Compiling The Linux Kernel source code...: [2023-01-11 16:54:24 CET] [ERROR] Failed with error: 2
[2023-01-11 16:54:24 CET] [ERROR] Something went wrong. Exiting.
[2023-01-11 16:54:24 CET] [ERROR] The last few log entries were:
Spin pid is: 3861879
dpkg: error: cannot access archive 'linux-headers-6.1.4_6.1.4-*.deb': No such file or directory
Installing Kernel headers: 6.1.4: [2023-01-11 16:54:24 CET] [ERROR] Failed with error: 2
[2023-01-11 16:54:24 CET] [ERROR] Something went wrong. Exiting.
[2023-01-11 16:54:24 CET] [ERROR] The last few log entries were:

**Comment by tmiland** [comment]
Hmm, could you try a different version? :)

Use --help if unsure how to.

**Comment by astalush** [comment]
Tried, it didn't work.

Today I've tried again with the 6.2, worked like a charm. Thanks!
